/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.Manejadores.ManejadorCarrera;
import Backend.Manejadores.ManejadorInterfaz;
import Backend.Manejadores.ManejadorReportes;
import Backend.Manejadores.ManejadorResultados;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author phily
 */
public class CareerAdvice extends javax.swing.JDialog implements ActionListener{
    private Timer timerToCarrer;
    private int secondsToStart = 5;
        
    /**
     * Creates new form CareerAdvice
     * @param parent
     * @param modal
     */
    public CareerAdvice(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
        
        initComponents();      
    }
    
    public void iniciarCuentaRegresiva(ManejadorCarrera manejadorCarrera, ManejadorInterfaz manejadorInterfaz,
            ManejadorResultados manejadorResultados, ManejadorReportes manejadorReportes){
        
       timerToCarrer = new Timer(1000, (ActionEvent e) -> {            
            if(secondsToStart > 0){
                this.secondsToStart--;
                this.labelCuentaRegresiva.setText(String.valueOf(this.secondsToStart));
                this.labelCuentaRegresiva.updateUI();
            }else{
                this.dispose();
                timerToCarrer.stop();
                
                manejadorCarrera.empezarCarrera(manejadorInterfaz, manejadorResultados, manejadorReportes);
            }
        
           });
            
            timerToCarrer.start();
    }
    
     public void actualizarCuentaRegresiva(String nuevaCuenta){
        this.labelCuentaRegresiva.setText(nuevaCuenta);
    }
     
    public void stopTimerToCareer(){
        if(this.timerToCarrer!= null && this.timerToCarrer.isRunning()){
            this.timerToCarrer.stop();
        }
    }
     

    @Override
    public void actionPerformed(ActionEvent e) {
        //this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelCuentaRegresiva = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caballos preparados");

        labelCuentaRegresiva.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        labelCuentaRegresiva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCuentaRegresiva.setText("5");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("El tiempo para apostar ha acabado, no es\nposible realizar más apuestas.\n\nAtento que la carrera está por comenzar :3\n");
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(labelCuentaRegresiva, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCuentaRegresiva)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelCuentaRegresiva;
    // End of variables declaration//GEN-END:variables
}
